##
# Code Climate configuration file.
# https://docs.codeclimate.com/docs/advanced-configuration
#
# IMPORTANT: Code Climate does not support custom Rubocop config like Standard.rb.
# That is why Code Climate badge shows failures all the time.
# https://github.com/codeclimate/codeclimate-rubocop/issues/131
#
version: 2

plugins:
  rubocop:
    enabled: true
    config:
      file: .rubocop.yml

exclude_patterns:
  - spec/**/*

##
# Disables default Code Climate checks.
# https://docs.codeclimate.com/docs/default-analysis-configuration
#
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
