# DOCS: https://docs.codeclimate.com/docs/advanced-configuration
version: 2

plugins:
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-80

exclude_patterns:
  - spec/**/*

checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

