##
# Standard based Rubocop config suggested by Evil Martians.
# - https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard
# - https://github.com/testdouble/standard
#
# Copied without any modifications from:
# https://gist.github.com/palkan/623c0816b05ed246bfe0cb406050990a
#
require:
  - rubocop-rspec

RSpec/Focus:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/HookArgument:
  Enabled: true

RSpec/HooksBeforeExamples:
  Enabled: true

RSpec/ImplicitExpect:
  Enabled: true

RSpec/IteratedExpectation:
  Enabled: true

RSpec/LetBeforeExamples:
  Enabled: true

RSpec/MissingExampleGroupArgument:
  Enabled: true

RSpec/ReceiveCounts:
  Enabled: true

RSpec/Capybara/CurrentPathExpectation:
  Enabled: true

RSpec/FactoryBot/AttributeDefinedStatically:
  Enabled: true

RSpec/FactoryBot/CreateList:
  Enabled: true
