AllCops:
  Exclude:
    - .git/**/*
    - bin/**/*
    - pkg/**/*
    - spec/**/*
    - vendor/bundle/**/*

Layout/LineLength:
  Max: 110

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Style/AsciiComments:
  Enabled: No

Style/Documentation:
  Severity: warning
  Enabled: No

Style/Lambda:
  EnforcedStyle: literal

Style/RedundantSelf:
  Enabled: No
