AllCops:
  Exclude:
    - .git/**/*
    - bin/**/*
    - pkg/**/*
    - spec/**/*
    - vendor/bundle/**/*

Layout/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 15

Style/Lambda:
  EnforcedStyle: literal

Style/RedundantSelf:
  Enabled: No
